---
- hosts: all
  become: yes
  tasks: 
    - name: Install nginx
      apt:
        name: nginx
        state: present
    
    - name: Install apache2
      apt:
        name: apache2
        state: absent
    
    - name: apache service
      service: 
        name: apache2
        state: started
