---
- hosts: all
  become: yes
  tasks: 
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: nginx service
      service:
        name: nginx
        state: started
   
