---
- hosts: all
  become: yes
  tasks: 
    - name: Install tree
      apt:
        name: tree
        state: present
    
    - name: Install apache2
      apt:
        name: apache2
        state: present
    
    - name: apache service
      service: 
        name: apache2
        state: started
